def emotdic(): #Bout de code de la v2 d'il y a deux ans, normalement il est complet
    emots = {
      ":):": "1",
      ":question:": "2",
      ":g)": "3",
      ":d)": "4",
      ":cd:": "5",
      ":monde:": "6",
      ":p)": "7",
      ":malade:": "8",
      ":pacg:": "9",
      ":pacd:": "10",

      ":noel:": "11",
      ":o))": "12",
      ":snif2:": "13",
      ":-(": "14",
      ":-((": "15",
      "apple": "16",
      ":gba:": "17",
      ":hap:": "18",
      ":nah:": "19",
      ":snif:": "20",

      ":mort:": "21",
      ":ouch:": "22",
      ":-)))": "23",
      ":content:": "24",
      ":nonnon:": "25",
      ":cool:": "26",
      ":sleep:": "27",
      ":doute:": "28",
      ":hello:": "29",
      ":honte:": "30",

      ":-p": "31",
      ":lol:": "32",
      ":non2:": "33",
      ":monoeil:": "34",
      ":non:": "35",
      ":ok:": "36",
      ":oui:": "37",
      ":rechercher:": "38",
      ":rire:": "39",
      ":-D": "40",

      ":rire2:": "41",
      ":salut:": "42",
      ":sarcastic:": "43",
      ":up:": "44",
      ":(": "45",
      ":-)": "46",
      ":peur:": "47",
      ":bye:": "48",
      ":dpdr:": "49",
      ":fou:": "50",

      ":gne:": "51",
      ":dehors:": "52",
      ":fier:": "53",
      ":coeur:": "54",
      ":rouge:": "55",
      ":sors:": "56",
      ":ouch2:": "57",
      ":merci:": "58",
      ":svp:": "59",
      ":ange:": "60",

      ":diable:": "61",
      ":gni:": "62",
      ":spoiler:": "63",
      ":hs:": "64",
      ":desole:": "65",
      ":fete:": "66",
      ":sournois": "67",
      ":hum:": "68",
      ":bravo:": "69",
      ":banzai:": "70",

      ":bave:": "71",
      ":cimer:": "72",
      ":ddb:": "73",
      ":cute:": "74",
      ":objection:": "75",
      ":pave:": "76",
      ":pf:": "77",
      ":play:": "78",
      ":siffle:": "79",
    }
    return emots